import React from 'react'

const Chapter1 = () => {
  return (
    <div>
        <h1 style={{textDecoration:'underline',textAlign:'center'}}>Introduction</h1>
<p style={{fontFamily: 'cursive',fontSize:'20px'}}>So this is a story about me ,whose love  story never had a happy ending in real life but this time i want to have my happy ending the love of my life and will be completing it by writing it in my own way, i will give the happy ending to my love life.
So this started at the age of 15 when we had just completed our boards.
We got 2 months break to decide our future and me being a stupid person made a bad decision which was choosing non medical and it was then when the real game of death started. To my surprise, someone entered in my life as if sent by god and that was the moment I found myself falling in love. His name was Samar guy whom I started falling in love. We met at tuition, and my silly heart began dreaming of a story where we’d end up as lovers who first crossed paths in that classroom. I used to glance at him secretly, sitting on the second seat while he sat in the first. We never spoke, not even a fleeting moment of eye contact—he probably didn’t even know I existed.Then, one day, he stopped coming. At first, I thought it was temporary, but days turned into weeks, and he disappeared completely. Just like that, he was gone.Yet, he became the king of my dreams. I found myself thinking of him day and night, holding onto the memory of his face and his name. I had no way to find him—no social media, no contacts, not a single way to reach out. All I had was a lingering hope, tied to a face I could never forget. One night, after months of silence, I unexpectedly came across his profile on LinkedIn. It was 2 a.m., and I had to rub my eyes to make sure I wasn’t dreaming. I couldn’t sleep after that—I was over the moon seeing him again after 10 long months. I sent him a connection request, and the next day, he texted me. But his message completely threw me off: “Who are you? Do I know you?” I was so shocked and nervous that I didn’t have the courage to reply for an entire week.I've been staring at that screenshot of the message for a week, trying to figure out how to reply to someone asking, 'Who am I?’ After a week of overthinking, I finally gathered my courage to reply back with, "Hi, myself Khyati." That was all. My heart was beating like it was racing at 2000 km/hr. I know it is ridiculous, but I could not stop myself; I was in love with him without meeting him even once just through second bench of secret stare.It was almost as if fate had finally intervened when I saw his profile on LinkedIn. Was this some kind of sign from the universe, a chance to complete the love story that I had dreamt of? That thought alone sent me to cloud nine. And then,he replied.That one notification lit up my entire world, I was absolutely ecstatic.
He replied to me, and I finally learned where he had disappeared all those months—he had been in boarding school since 2nd grade which was in entirely in totally different state and he was back in hometown and h here he was for vacation as it was winter break and i couldn’t be happier.As our conversation was going on, I realized he didn’t believe that i was a girl. Since i had created a new account without putting any of my achievements, his doubts seemed somewhat valid.However, deep inside me. I felt he had already guessed who i actually was.He even called me weird–not directly,but i knew he was talking about me.So what happened was,there was this one interaction we had–or rather,it was an attempt at interaction from my side.All i got in return was a cold,indifferent look.Back then,i was sitting in the middle row, and he was just beside me.All i knew was his name at the time,i called out to him.He didn’t look my way.My friend joined in,calling to him,but he wouldn’t budge, we ended up laughing,wondering what kind of person he was.Because of that incident,i guess he now thinks I’m weird,rude and who knows what else.The funny part? He had no idea it was me. The funniest part was when he asked me to meet him that very day just to confirm if I was really a girl. I couldn’t stop laughing like crazy, but at the same time, I was so nervous about finally meeting him. I covered myself with a full mask and went to the place he had told me to meet him.
When I arrived, he was already there—standing, looking so hot and handsome. I wished I could tell him how amazing he looked. But I was too nervous. Since I was with my friend, I kept telling her, “Please, can you go ahead first?” I was beyond nervous. She gave me a side-eye and kept looking at me as if I had committed some sort of crime.
Yes, yes, I know I was being silly, but what could I do? I was about to meet him after 10 long months and it was not like we could have met at tuition but I left the tuition and joined the new one,thinking that i wont be finding him again, but i only know, and I was in love. Seeing him standing right in front of me felt so magical. I could have stared at him for hours; he looked so perfect.We talked for a few minutes, and just like that, it was over. He left for his tuition, and I was left standing there, feeling the bittersweet ache of seeing someone you love, knowing it might be the last time. I wished I could ask him to stay—just a little longer—so I could memorize his face, his voice, and discover more about him. But I had no right to stop him; he wasn’t mine to hold back..
When I got back home, I decided to write a poem about him. I wasn’t good at writing poetry back then, but I wanted to try—just for him. That day felt like the best of my life—a memory I would cherish forever. It wasn’t the first time I’d seen him, having watched him countless times at tuition, but something about this moment felt different—unreal, almost majestic. If I could, I would write an entire novel about him, for I was utterly, hopelessly in love.
After we reached home, we talked about our day and reminisced about the last time we met,he was actually asking about my friend whom came with me while i was going to meet him, I was nervous as hell so i had to take her so that i dont loose my confidence. In the middle of our conversation, he casually mentioned his crush—he was planning to propose to her on her birthday, which was in March. To this day, I still remember the date—8th March. Hearing that shattered me; knowing that my first love had already given his heart to someone else was painful. I did cry that day a lot thinking why it had to be me. Why do i have to be the one nobody loved or liked me for who i am. I was crying when he was telling me about her. I wish I wish i could tell him that i also like him.
</p>
    </div>
  )
}

export default Chapter1