import React from 'react'

const Chapter2 = () => {
  return (
    <div>
        <h1 style={{textDecoration:'underline',textAlign:'center'}}>Chapter2</h1>
        <p style={{fontFamily: 'cursive',fontSize:'20px'}}>That night passed in a blur. It was strange how, in a single day, I experienced both the best and the worst—discovering the joy of being around him and the heartbreak of realizing that my crush liked someone else. I had fallen for him without even having a proper way to see or talk to him, and that thought alone was enough to break me. Deep down, I knew I could never be his, but I couldn't help wondering—why did he even cross my path? If I hadn’t met him on LinkedIn, would I be crying right now?
Maybe I was just overthinking. Or maybe I wasn’t. I didn’t know. All I knew was how low I felt that day. I couldn't focus on my studies, constantly thinking about how lucky that girl was—loved by someone I could only dream of. Despite the pain, I just hoped she wouldn’t break his heart. After all, even if I couldn’t be his, I could still love him, right? No rule says you can’t love someone who loves someone else.
I told myself I would cherish Samaralways. My heart refused to give up on him. I had once heard that simply being able to talk to your crush was enough, and for someone like me, who never had a way to reach him before, even our smallest conversations felt like a victory. It made me happy, and I held onto that happiness tightly. Slowly, I began to talk to him more and more—falling deeper into my own foolishness.
It was my first time experiencing love, and despite everything, it felt beautiful. I stopped dwelling on the night he told me about his crush and found comfort in the fact that he was talking to me. I used to find silly ways to initiate conversations—sending him random reels and pretending they were meant for someone else. "Oops, that was by mistake," I’d say, just to have an excuse to talk to him. Back then, it didn’t feel embarrassing, but now, looking back, I can’t help but smile at how naive I was. But isn’t that what love does to you?
Even now, I could tell him that I love him and always will. Our conversations, though often meaningless, meant everything to me. We talked about anything and everything, and slowly, it became a routine.
And there he was, in love, sharing his plans with me. I knew how he intended to propose to her, even though they were miles apart—him in the hostel, and she at home. He had it all planned out—sending her a pendant or a bracelet and proposing on the night of her birthday.
And I? I was just there listening, loving him in silence. Every word he spoke felt like a gentle tug at my heartstrings, yet I smiled, hiding it all beneath a facade of casual indifference. In a moment of courage, I asked him, "What does love really mean to you?"
He laughed and said "For me, love is something that Siddhi taught me. It’s in the way she talks to me, the way she understands me without even trying, the way I want to give her the princess treatment she deserves. I don't know, Khyati... Something changed inside me, and I can’t be the same Singh anymore. She’s changed me completely. Even though we're miles apart, I know she’ll never leave me. She’s my dream girl, you know? You should find someone too. Maybe then you’d understand how I feel."
I forced a laugh, masking the ache rising within me, and replied, "Oh boy, you are so in love. I really hope you both stay together forever." I smiled, as if his happiness was all that mattered.
But inside? Inside, I was crumbling.
Later, I texted him goodnight and laid down on my bed, staring at the ceiling, letting out a quiet, sad chuckle. Who would tell him that I understood his feelings better than anyone else? That I too was in love... but the only difference was, he had his dream girl, while mine would forever remain just a dream.
I sighed, clutching my phone tightly, as if it could somehow hold my unspoken words. My thoughts spiraled, weaving between hope and heartache. Maybe... maybe someday something would change. It had to, right?
With that lingering thought, I drifted into sleep, clutching dreams that would never quite be mine. 



Like this, a year went by, and I continued talking to him. The fact that he was in a relationship bothered me, but not too much, because all I truly wanted was to be his friend. Yet, he never knew how I felt every time we spoke; it felt like heaven. However, around the middle of the year, we drifted apart. I'm not sure for how many months, but our conversations ceased. I got caught up in my studies, and he was busy with school as well.
Then, in August, a message popped up from his friend’s account. He told me that his parents had gained access to his social media account and had discovered his relationship with his girlfriend. They were planning to visit her house. It was a whirlwind of emotions for him, and I found myself in the middle of it all. We had a mutual friend named Hardik, who also happened to be her cousin, and I became the bridge between them. Since he couldn't communicate directly, I became the messenger, passing information through Hardik and trying to help in any way I could. Despite the awkwardness of talking to Hardik someone I had never spoken to before, neither in person nor over text  did it for him. And deep down, I felt a sense of happiness. He trusted me enough to reach out in such a difficult time.
But as the days passed, a tiny voice in my head began to whisper doubts. Was this situation even real? How did his parents gain access to his account so easily? If they truly had control, how was he still able to watch my stories and post updates like nothing had changed? It felt strange, almost as if I was caught in an elaborate web of half-truths and deception. There were moments I wondered if I was being foolish, believing that things were as serious as he made them out to be, while he might have been sitting back and enjoying the drama.
And then, just like that, one day, he told me that everything was fine—like nothing had ever happened. The sudden shift in narrative left me bewildered, questioning everything I had believed up until that point. Was it all a lie? Had I been played? Or was I just overthinking it all?
Despite the uncertainty, I chose to believe him. Maybe it was naive, or maybe it was the unwavering loyalty I had as a friend, but I held onto the version of events he presented to me. Even now, when I think back to those moments, I don't know the truth. And perhaps, deep down, I don't want to know. Some things are better left as mysteries, tangled in the complexity of emotions, friendship, and unspoken feelings.Because if i got to know that it was a lie and he had intention then somewhere or the other i will be hurt.
As time passed, we didn’t talk as much as we used to. A whole year went by, and it was January once again. We played some silly games together, like truth and dare. I had to convince my friends to join in, just so I could get a chance to talk to him and know him better. By then, I had realized that he was truly a gentleman—kind, thoughtful, and simply amazing. I knew that his future wife would be the luckiest girl in the world, loved and cherished by him every single day for the rest of their lives.
Then came January 2023, a fresh start to the new year, and during one of our casual conversations, he told me something that made my heart race—he had broken up with Siddhi. I was jumping like a maniac inside, feeling an overwhelming wave of happiness. I couldn't believe it; he was finally single! But at the same time, a part of me felt sad for him because I knew how much he had loved her. Just last year, he was planning how to propose to her, and now he was telling me about their breakup.
Curious, I asked him why they had broken up, but he simply said, “I got to know something about her, and I had no other choice but to end it.” That was all he gave me. All I could say was, "Ohhh," trying to hide the storm of emotions inside me. The very next moment, I texted my best friend, spilling the news that he was officially single. I was ecstatic—super duper happy, to be honest.
With this newfound hope, I started thinking—maybe if I put in a little effort, he could love me the way I wanted him to. I wanted to be the one he cherished, the one he called his own. After all, he was the best person I had ever known. Even now, I still believe he’s the best. He knows how to chase his dreams, he understands his priorities, and I love him for that. My love for him is unwavering, and no matter who comes into my life, Samar’s name is etched on my heart forever.
Slowly, I began talking to him regularly. At first, I was hesitant to text him first—afraid he might find me annoying, or worse, uninterested. Thinking back, I realize how silly I was for holding back. If only I had been bolder, maybe things could have turned out differently. Could we have been together if I had been more persistent? But it doesn’t depend on me only, if he would had been interested then he would also had also texted me right. 
Days turned into weeks, and I found myself preparing for my JEE and board exams. Even during this stressful period, we continued talking. He often checked in on me, asking about my preparations, how I was feeling, and whether I was stressed. His concern warmed my heart—he genuinely cared. He made sure I wasn’t feeling overwhelmed by the pressure, and in those moments, I felt a deeper connection with him.
His words, his presence, his caring nature—everything about him made me fall even more in love. And even though life kept moving forward with its uncertainties, one thing remained constant—I loved him, and I always would.
The end of my JEE exams felt like the closing of a long, exhausting chapter. I had just completed my second attempt, and we desperately needed a break. We had been studying relentlessly for two years without a single pause. Of course, it mattered whether I got into an IIT or IIIT, but for me, it was more about the effort I had put in—had I done enough? Did I need to push myself even further? Strangely, I wasn’t too concerned about qualifying for JEE Advanced because I had plenty of other entrance exams lined up.
Once the exams were finally over, my friends and I decided to go watch a movie together. We knew this might be the last time we’d all be together like this—soon, we’d be heading off to different colleges, different cities, and who knew when we’d get to sit down and enjoy each other's company again? It took us a while to settle on a movie, and we eventually planned it for the following week so that everyone could be free.
While we were planning, an idea suddenly popped into my head—why not invite Samar? He was still in town, his school had ended, and he was preparing to go abroad for further studies. It felt like the perfect opportunity to finally see him—not from a distance, not through a screen, but face-to-face. The thought made my heart race. This time, I wouldn't have to glance him through screen, I could actually watch him up close.
But first, I had to convince him. And that was no easy task. His father was known to be strict, and I wasn’t sure if he’d be allowed to come. So, I casually texted him, saying, “We’re planning to go watch a movie,so if you are free please come and enjoy with us, but we haven’t decided which one yet. Any suggestions?” I tried to keep it light, not wanting to seem too eager.
His reply came after a while. “I’ll have to see if I can come… my dad’s a bit strict.”
And just like that, my excitement dimmed. A part of me started to believe that I might not get to see him again. The thought stung. I had only met him once before, and that too for just two fleeting minutes. But this time, I had imagined spending more time with him, talking to him without needing to hide behind excuses or disguises, without the fear of being recognized. I chuckled to myself, realizing how silly my thoughts were.
Still, even though he wasn’t sure if he could join us, he did suggest a movie. And that alone made me happy he had picked something for us. It felt like a small connection, a tiny piece of him in our plans, and for now, that was enough.
</p>
    </div>
  )
}

export default Chapter2